# Generated by Django 4.1 on 2024-06-11 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('control_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unread_user', models.BooleanField(blank=True, default=True, null=True)),
                ('unread_admin', models.BooleanField(blank=True, default=True, null=True)),
                ('is_cargo', models.BooleanField(blank=True, default=False, null=True)),
                ('is_customer', models.BooleanField(blank=True, default=False, null=True)),
                ('is_guest', models.BooleanField(blank=True, default=False, null=True)),
                ('is_seller', models.BooleanField(blank=True, default=False, null=True)),
                ('participant', models.JSONField(blank=True, null=True)),
                ('online_users', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=0)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('is_file', models.BooleanField(default=0)),
                ('is_auth_user', models.BooleanField(default=1)),
                ('anonymous_user_secret', models.CharField(blank=True, max_length=254, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=254, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
