# Generated by Django 5.0.6 on 2024-06-11 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_secret', models.CharField(blank=True, max_length=254, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
