# Generated by Django 5.0.6 on 2024-06-09 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.TextField(),
        ),
    ]
