# Generated by Django 5.0.6 on 2024-06-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0002_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
