# Generated by Django 5.0.6 on 2024-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='processed_image',
            field=models.ImageField(null=True, upload_to='processed_images/'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
