# Generated by Django 5.0.6 on 2024-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0004_imagemodel_processed_image_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='heights',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='widths',
            field=models.JSONField(null=True),
        ),
    ]
