# Generated by Django 5.0.6 on 2024-06-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0006_imagemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
    ]
