# Generated by Django 5.0.6 on 2024-06-26 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0007_imagemodel_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='from_where',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='to_where',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
