# Generated by Django 5.0.6 on 2024-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0008_imagemodel_from_where_imagemodel_to_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='selected_height',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='selected_width',
            field=models.JSONField(null=True),
        ),
    ]
