# Generated by Django 5.0.6 on 2024-06-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0009_imagemodel_selected_height_imagemodel_selected_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
